POST  http://localhost:4000/users/authenticate
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTU3MzYyMjY1Mn0.kVlrRXz6_pPyX7uHpSseP32Vs0lnuCwOGJWN4UfGLEA


###
POST https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity
Content-Type: application/json

{
   "employer":"Strosin - Windler",
   "grossAnnualSalary":"13945.5",
   "payfrequency":"Paid fortnightly",
   "customer":{
      "firstName":"Roy",
      "lastName":"Bechtelar",
      "email":"Mai.Sawayn44@hotmail.com",
      "mobile":"0411347318"
   },
   "consultant":{
      "firstName":"Anais",
      "lastName":"Mohr",
      "email":"Destiney_Ruecker43@hotmail.com",
      "mobile":"235-445-8023"
   }
}

###
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Customer/7338d600-4373-41a8-9492-adf32cbdb704

###
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Consultant/7338d600-4373-41a8-9492-adf32cbdb704
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZWRjNDFkOC00ZDUwLTQ1MjYtODBkOS02OGYyNjljOGNlYzciLCJlbWFpbCI6IlRhZC5CYWlsZXk1QHlhaG9vLmNvbSIsImlhdCI6MTU3ODU0NDYzNywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IjczMzhkNjAwLTQzNzMtNDFhOC05NDkyLWFkZjMyY2JkYjcwNCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlRhZC5CYWlsZXk1QHlhaG9vLmNvbSIsIm5iZiI6MTU3ODU0NDYzNiwiZXhwIjoxNTc4NTQ4MjM2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjY0OTQxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSJ9.yYcZkQAExJfQTKbd6vLsRg0wf-Ep4SInEtJsxU2hHQY

###
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity/28aef021-d2ce-4c25-b595-4cab5b557021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkNmNlYjkzNi0xNmIwLTRiNTYtYTQzNi0xYjRhMWVjNGVmYzIiLCJlbWFpbCI6Ikp1d2FuLlNhd2F5bjQ0QGhvdG1haWwuY29tIiwiaWF0IjoxNTc4NTI5MTI0LCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMjhhZWYwMjEtZDJjZS00YzI1LWI1OTUtNGNhYjViNTU3MDIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiSnV3YW4uU2F3YXluNDRAaG90bWFpbC5jb20iLCJuYmYiOjE1Nzg1MjkxMjMsImV4cCI6MTU3ODUzMjcyMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjQ5NDEifQ.42fvCSsOhxsbBQja7aO3RckYOQZpdn3Ww0xwkvDMFxQ

###
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity/800e66ad-26b1-462b-b5b7-704dbafa8c11/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0ZGY3OWMzZi0yM2FjLTQyNGUtOTNlNS0xODk4ODNhYWEwNzMiLCJlbWFpbCI6InN0ZXZlbi5zdHJhbmdlQG1hcnZlbGwuY29tIiwiaWF0IjoxNTgwNjg0NTg2LCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiODAwZTY2YWQtMjZiMS00NjJiLWI1YjctNzA0ZGJhZmE4YzExIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic3RldmVuLnN0cmFuZ2VAbWFydmVsbC5jb20iLCJuYmYiOjE1ODA2ODQ1ODYsImV4cCI6MTU4MDY4ODE4NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjQ5NDEifQ.NMf5CDPuX52bBgCg0lE5X5ItbksLIi68R4gTQ68lgQg

###
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity/800e66ad-26b1-462b-b5b7-704dbafa8c11/quote/60f9c7c3-bf32-4d8c-b153-b63090a11315
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1ZmFhM2MzYy1mNzgwLTQ0M2EtODc3MS03YzExZTU5Yzg2Y2EiLCJpYXQiOjE1ODE4MjAwNzYsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiI4MDBlNjZhZC0yNmIxLTQ2MmItYjViNy03MDRkYmFmYThjMTEiLCJlbWFpbCI6InN0ZXZlbi5zdHJhbmdlQG1hcnZlbGwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic3RldmVuLnN0cmFuZ2VAbWFydmVsbC5jb20iLCJuYmYiOjE1ODE4MjAwNzUsImV4cCI6MTU4MTgyMzY3NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjQ5NDEifQ.OsplRab79W_oCej0hFazPgUeX5te0Ti1EZCoiHYFcJc

####
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity/800e66ad-26b1-462b-b5b7-704dbafa8c11/quote/b7e42a2f-e627-ea11-a810-000d3a6aaf3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxNzhiZDc5Ni00NTY1LTQ0NTgtOWMzOC1lYmUyYmMxY2ZmMzMiLCJpYXQiOjE1ODE4OTcwODksImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiI4MDBlNjZhZC0yNmIxLTQ2MmItYjViNy03MDRkYmFmYThjMTEiLCJlbWFpbCI6InN0ZXZlbi5zdHJhbmdlQG1hcnZlbGwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic3RldmVuLnN0cmFuZ2VAbWFydmVsbC5jb20iLCJuYmYiOjE1ODE4OTcwODksImV4cCI6MTU4MTkwMDY4OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjQ5NDEifQ.jTuB9CWvyXa2DDNYxkwqAmiuIkQ1hb0VLqn1K2JDuT8

####
GET https://dev1-mms-digi-dep-api.azurewebsites.net/api/Opportunity/800e66ad-26b1-462b-b5b7-704dbafa8c11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwYzMxMGUyMS1hYTVhLTQ3MjAtYTRjMS04YzdiYWJjMjRmNTgiLCJpYXQiOjE1ODE5ODM0NTcsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiI4MDBlNjZhZC0yNmIxLTQ2MmItYjViNy03MDRkYmFmYThjMTEiLCJlbWFpbCI6InN0ZXZlbi5zdHJhbmdlQG1hcnZlbGwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic3RldmVuLnN0cmFuZ2VAbWFydmVsbC5jb20iLCJuYmYiOjE1ODE5ODM0NTYsImV4cCI6MTU4MTk4NzA1NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2NDk0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjQ5NDEifQ.6uMWw9mEWDQEYL-X7_Jx0Ujvs4U-gNHslMNlz_FdTQQ
