export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  ACCESS_CODE_REQUEST: "ACCESS_CODE_REQUEST",
  ACCESS_CODE_REQUEST_SUCCESS: "ACCESS_CODE_REQUEST_SUCCESS",
  ACCESS_CODE_REQUEST_ERROR: "ACCESS_CODE_REQUEST_ERROR"
}

export const alertConstants = {
  ALERT_SUCCESS: "ALERT_SUCCESS",
  ALERT_ERROR: "ALERT_ERROR",
  ALERT_CLEAR: "ALERT_CLEAR",
}

export const userConstants = {
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "FETCH_USER_ERROR"
}

export const consultantConstants = {
  FETCH_CONSULTANT_SUCCESS: "FETCH_CONSULTANT_SUCCESS",
}

export const opportunityConstants = {
  RECEIVE_OPPORTUNITY_ID: "RECEIVE_OPPORTUNITY_ID",
  FETCH_OPPORTUNITY_REQUEST: "FETCH_OPPORTUNITY_REQUEST",
  FETCH_OPPORTUNITY_SUCCESS: "FETCH_OPPORTUNITY_SUCCESS",
  FETCH_OPPORTUNITY_ERROR: "FETCH_OPPORTUNITY_ERROR",

  FETCH_OPPORTUNITY_INFO_REQUEST: "FETCH_OPPORTUNITY_INFO_REQUEST",
  FETCH_OPPORTUNITY_INFO_SUCCESS: "FETCH_OPPORTUNITY_INFO_SUCCESS",
  FETCH_OPPORTUNITY_INFO_ERROR: "FETCH_OPPORTUNITY_INFO_ERROR"
}


